sources:
  - type: maven
    path: pom.xml
    artifacts:
    - target/exasolCloudwatchDashboard.json

build:
  workflows:
  - name: ci-build.yml
    stepCustomizations:
      - action: INSERT_AFTER
        job: build-and-test
        stepId: setup-java
        content:
          name: Install CDK
          id: install-cdk
          run: npm install -g aws-cdk
      - action: INSERT_AFTER
        job: build-and-test
        stepId: build-pk-verify
        content:
          name: Synthesize CloudFormation template
          id: synthesize
          run: cdk synthesize --json > target/exasolCloudwatchDashboard.json

  - name: release.yml
    stepCustomizations:
      - action: INSERT_AFTER
        job: release
        stepId: setup-jdks
        content:
          name: Install CDK
          id: install-cdk
          run: npm install -g aws-cdk
      - action: INSERT_AFTER
        job: release
        stepId: build
        content:
          name: Synthesize CloudFormation template
          id: synthesize
          run: cdk synthesize --json > target/exasolCloudwatchDashboard.json
      