name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Assets upload URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Run tests and build with Maven
        run: |
          mvn --batch-mode clean verify -DtrimStackTrace=false
      - name: Install CDK
        run: npm install -g aws-cdk
      - name: Synthesize
        run: cdk synthesize --json > exasolCloudwatchDashboard.json
      - name: Generate sha256sum files
        run: sha256sum exasolCloudwatchDashboard.json > exasolCloudwatchDashboard.json.sha256
      - name: Upload assets to the GitHub release draft
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: exasolCloudwatchDashboard.json
      - name: Upload sha256sum files
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: exasolCloudwatchDashboard.json.sha256
      - name: Upload error-code-report
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/error_code_report.json